### ISSUE TITLE
[docs] The demo yaml has a format error

### ISSUE THREAD

**Issue by laorange** [mmasciol/yaml-fortran#9]
In the docs, `example` - `Fortran YAML Library` - `Reading a YAML File` (http://yaml-fortran.com/example.html):

```yaml 
parent_1:  # a map
    child_a:
        boolean_flag: true
        an_aray: [0.999, 1.0]
        array_int_2d: [[1,   2,  3],[4,   5,  6],[7,   8,  9],[10, 11, 12]]
parent_2:  # a sequence
  - item: 3 x 3 matrix.
    value: [[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]
  - item: 4 x 3 matrix
    value: item_is_float_array_2d: [[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]
```

There is a formatting issue with the last line. I guess the last line may be supposed to be like this:
```yaml 
    ...
    value: 
        item_is_float_array_2d: [[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]
```

As a result, the full yaml text will become:

```yaml 
parent_1:  # a map
    child_a:
        boolean_flag: true
        an_aray: [0.999, 1.0]
        array_int_2d: [[1,   2,  3],[4,   5,  6],[7,   8,  9],[10, 11, 12]]
parent_2:  # a sequence
  - item: 3 x 3 matrix.
    value: [[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]
  - item: 4 x 3 matrix
    value: 
        item_is_float_array_2d: [[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]
```
